### PR TITLE
Under water shine

### PR DESCRIPTION
**Pull request by sfence**
Update original branch under_water_shine.

Fixed light flicking.
Make it a little more extensability.
Make floodable items not emitting light underwater.
Add Hades Revisited support for underwater light.

### CODE REVIEW

**Comment by sfence** [comment]
Fixed.

**Comment by sfence** [comment]
Fixed possible access of nil value.
I have fixed it for `if itemdef.floodable then` too, because it looks like condition 
`if not light_level and not itemdef then` will not cause function return when the item doesn't exist and is in shine_items list.

**Comment by SmallJoker** [comment]
:+1: LGTM will merge in a few days unless there are objections.

**Comment by bell07** [comment]
If the flicking issue is solved, maybe this changes should be merged to master?

**Comment by oversword** [comment]
Is there an option to switch this off for certain light sources? I can understand glow glass illuminating water, but I would want to be able to exclude the torch and other open flames from that list. I think there should either be a separate list, or a list of exclusions

**Comment by sfence** [comment]
> Is there an option to switch this off for certain light sources? I can understand glow glass illuminating water, but I would want to be able to exclude the torch and other open flames from that list. I think there should either be a separate list, or a list of exclusions

These changes exclude only floodable light sources (like normal torches in default game). So, if open flames are not floodable, they will shine under water.
So, for that situation, some exclude list should be added.

**Comment by oversword** [comment]
> These changes exclude only floodable light sources (like normal torches in default game).

Ahh okay so that will work if the mods have been programmed correctly... which means it will not work for most mods xD I can imagine most of the light sources provided by decor mods have not been thought through that far

**Pull request merged**
